spring.datasource.url=jdbc:h2:file:./transaction;MODE=MySQL;ACCESS_MODE_DATA=r
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.main.allow-bean-definition-overriding=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.spatial_dialect=org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
spring.jpa.show-sql=false
server.port=8081
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
spring.h2.console.settings.trace-level-file=4
spring.h2.console.settings.trace-level-system-out=3
spring.h2.console.settings.cache-size=16384
spring.h2.console.settings.page-size=4096
spring.h2.console.settings.max-compact-time=200
spring.h2.console.settings.compress-lob=true
spring.h2.console.settings.lock-timeout=10000
spring.h2.console.settings.default-lock-timeout=10000
spring.h2.console.settings.default-table-engine=org.h2.mvstore.db.MVTableEngine
spring.h2.console.settings.mvcc=true
spring.h2.console.settings.create-if-not-exists=true