# --- ???????? ???? ?????? (??????????) ---
spring.datasource.url=jdbc:h2:file:./transaction;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always

# ????????? ????????????? Repository ??? ????????? ?????????
spring.data.jpa.repositories.enabled=false 
spring.data.jdbc.repositories.enabled=false

# --- ?????? ???? ?????? (???????????? ???????) ---
rules.datasource.jdbcUrl=jdbc:h2:mem:rulesdb;DB_CLOSE_DELAY=-1
rules.datasource.driver-class-name=org.h2.Driver
rules.datasource.username=sa
rules.datasource.password=

# ????????? JPA ??? ?????? ??????
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none # ????????? ?????? ????? Liquibase

# ????????? Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.default-schema=public
spring.liquibase.enabled=true